// page labels
export const pageLabels = {
  global: 'Global',
  home: 'Acasă',
  services: 'Servicii',
  portfolio: 'Portofoliu',
  contact: 'Contact',
  cookies: 'Cookies',
  about: 'Despre noi',
  'thank-you': 'Mulțumim',
  'too-many-requests': 'Prea multe solicitări',
  how_we_work: 'Cum lucrăm',
  certifications: 'Certificări',
  products: 'Produse',
  faq: 'Întrebări Frecvente',
};

// section labels
export const sectionLabels = {
  header: 'Header',
  hero: 'Hero',
  carousel: 'Carusel',
  stats: 'Statistici',
  gallery: 'Galerie foto',
  services: 'Serviciile noastre',
  services_list: 'Lista servicii',
  partners: 'Parteneri',
  why_choose_us: 'De ce să alegi serviciile noastre',
  reviews: 'Recenzii',
  cta: 'Îndemn la Acțiune',
  products: 'Produse',
  products_list: 'Lista produse',
  how_we_work: 'Cum lucrăm',
  contact_main: 'Secțiunea contact',
  contact_street_view: 'Vedere stradală',
  mission: 'Misiunea noastră',
  team: 'Echipa',
  process: 'Procesul nostru',
  why_it_works: 'De ce funcționează',
  standards: 'Standarde',
  certs_list: 'Lista certificări',
  assignment: 'Angajament',
  quality: 'Calitate garantată',
  faq_list: 'Întrebări și răspunsuri',
  accordion: 'Întrebări frecvente',
  info: 'Informații suplimentare',
  navbar: 'Bara de Navigație',
  footer: 'Footer',
  brand: 'Brand',
  'cookie-pop-up': 'Banner Consimțământ Cookies',
  projects: 'Proiectele noastre',
  what_recommends_us: 'Ce ne recomandă',
  'thank-you-section': 'Mulțumim',
  'too-many-requests-section': 'Prea multe solicitări',
};
